### ISSUE TITLE
Scala 2.13?

### ISSUE THREAD

**Issue by heksesang** [evotor/aecor-postgres-journal#18]
It would nice to see this published for Scala 2.13. :)

**Comment by notxcain** [comment]
Sorry, I won't have time to work on this for at least a month. So PR is very welcome. It should be straighforward.

**Comment by heksesang** [comment]
I already bumped versions and tried to run tests with it, seemed fine. So I'll make a PR as soon as I have time to set it up with cross-compile. :)

**Comment by notxcain** [comment]
Closed in #24
